#
version: '3.7'
networks:
  laravel:

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    tty: true
    ports:
      - "3306"
    volumes:
    - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=cloudteam_basesource
      - MYSQL_USER=root
      - MYSQL_PASSWORD=""
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    networks:
      - laravel

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: 'laravel-docker'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
    - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel
